#!/bin/bash

#--------------------------------------------
# title: 天河二号点对点通信overlapping测试脚本
# author: 王志昊
# time: 2018/05
#--------------------------------------------
# Info: ./overlapping_script.sh param1 param2

echo "脚本接收到$#个参数！"